import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Amanuel Portfolio App",
  description: "Generated by Amanuel Wakshum",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-[#05161A] to-[#0c7075]">
          <div className="h-24 bg-transparent">
          <Navbar />
          </div>
          <div className="h-[calc(100vh-6rem)]">
          {children}
          </div>
        </div>
        </body>
    </html>
  );
}
